# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :clean do
    gradle(task: "clean")
  end

  lane :beta do
    gradle(task: "clean assembleDebug")
  end

  lane :push_hocky do
    hockey(
      api_token: "be528c30bca33a2c68808574575363963998fef9",
      apk: "/var/jenkins_home/jobs/app\ pipeline/jobs/aaaaa/workspace/app/build/outputs/apk/debug/app-debug.apk",
      notes: "init app"
    )

  end

end
